### ISSUE TITLE
download URL on website results in 404, issue with icons

### ISSUE THREAD

**Issue by keev-studio** [jeanvera23/material-design-uikit#1]
Hi, first of all thanks for excellent project. I found 2 issues

1. download button on the website Installation page (https://mduikit.com/Views/installation.php) is not working. Pointing to https://mduikit.com/mduikit.zip (404)
2. I was trying to recreate the examples from the website, working fine except the icons (even if I add uikit-icons.min.js)
https://codepen.io/keev/pen/mdMRdzw
any comments on this? thank you

**Comment by jeanvera23** [comment]
Hi! Thanks for your comment. The issue is solved. For the icons, you have to include the URL from Material Icons. Use the example shown when you press download.
